language: go

go:
    - 1.1
    - tip

services:
    - memcached

install:
    - export GOPATH=$HOME/gopath
    - export PATH=$PATH:$GOPATH/bin
    - go get -v github.com/robfig/revel/revel

script:
    - revel test github.com/codeb2cc/gmcadmin
